name: Build and Publish docs

on:
  release:
    types:
      - created
      - edited 

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main Repository
      uses: actions/checkout@v2
      with:
        repository: 'DbSyncKit/DbSyncKit'  

    - name: Pull & update submodules recursively
      run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
 
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Build and Publish Docs
      env: 
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_API_KEY: ${{ secrets.NETLIFY_API_KEY }}
        
      run: |
        cd DbSyncKit.Docs

        echo '{"NetlifySiteId": "=> NETLIFY_SITE_ID","NetlifyAccessToken": "=> NETLIFY_API_KEY"}' > appsettings.config

        # Install any required dependencies
        dotnet restore

        # Build documentation
        dotnet build -c Release

        # Run the Statiq documentation console app with necessary arguments and secrets
        dotnet run  deploy -s IgnoreInvalidXrefs=true --framework net8.0
        
